# docker-compose.yml

name: doc-gen

services:
  base:
    image: doc-gen-base:latest

    build:
      context: .
      dockerfile: Dockerfile
      target: base

    working_dir: /workspace

    volumes:
      - .:/workspace

    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      HOST_PWD: ${PWD}

    stdin_open: true
    tty: true
