# app/doc_gen/core/structure/metadata/repository_docs.py

COMMON_DIRECTORIES = {
    "app": {
        "description": "Main application source code.",
        "details": [
            "Contains the core implementation of the project.",
            "May include business logic, services, modules, and utilities.",
        ],
    },
    ".config": {
        "description": "Project configuration files.",
        "details": [
            "Stores reusable configuration files used by the project.",
            "Helps keep the repository root clean and organized.",
            "",
            "Common examples:",
            "- .config/tool-config/",
            "- .config/templates/",
            "- .config/settings/",
        ],
    },
    ".github": {
        "description": "GitHub-related configuration.",
        "details": [
            "Contains GitHub workflows, templates, and automation files.",
            "",
            "Common examples:",
            "- .github/workflows/       → GitHub Actions CI/CD pipelines",
            "- .github/ISSUE_TEMPLATE/  → issue templates",
            "- .github/PULL_REQUEST_TEMPLATE.md",
            "",
            "Used to automate testing, releases, and repository management.",
        ],
    },
    ".vscode": {
        "description": "Visual Studio Code workspace settings.",
        "details": [
            "Contains editor settings shared across the team.",
            "",
            "Common examples:",
            "- settings.json",
            "- launch.json",
            "- tasks.json",
            "- extensions.json",
        ],
    },
    "docs": {
        "description": "Project documentation and technical references.",
        "details": [
            "The documentation folder usually contains structured knowledge about the project.",
            "",
            "Common documentation sections:",
            "- docs/architecture        → system design and architecture diagrams",
            "- docs/development         → development guides and workflows",
            "- docs/system              → detailed technical documentation",
            "- docs/reference           → command references and APIs",
            "- docs/user-guide          → instructions for end users",
            "- docs/diagrams            → visual architecture diagrams",
            "- docs/phases              → project phases and planning",
            "- docs/Q&A                 → common questions and explanations",
            "",
            "Common files:",
            "- PROJECT_STRUCTURE.md",
            "- DEVELOPMENT_GUIDE.md",
            "- HOW_TO_USE.md",
            "- TODO.md",
            "- CLI_COMMAND.md",
            "- references.md",
            "- badges.md",
        ],
    },
    "tests": {
        "description": "Automated tests.",
        "details": [
            "Contains unit tests and integration tests.",
            "Ensures code reliability and correctness.",
        ],
    },
    "data": {
        "description": "Input datasets or static data.",
        "details": [
            "May contain sample datasets, fixtures, or configuration data.",
        ],
    },
    "output": {
        "description": "Generated outputs from the application.",
        "details": [
            "Logs, reports, generated files, or exported artifacts.",
        ],
    },
    "scripts": {
        "description": "Utility scripts for development or automation.",
        "details": [
            "May include deployment scripts, maintenance tools, or helpers.",
        ],
    },
    "tools": {
        "description": "Development tools and automation utilities.",
        "details": [
            "Contains scripts used during development and maintenance.",
            "",
            "Common examples:",
            "- tools/generate_ignore     → generate .gitignore, .dockerignore",
            "- tools/project_structure   → generate PROJECT_STRUCTURE.md",
            "- tools/git_commit          → commit and tagging automation tools",
        ],
    },
    "templates": {
        "description": "Reusable templates used by the project.",
        "details": [
            "Often includes templates for git commit messages or configuration files.",
            "",
            "Example structure:",
            "- templates/git/example/commit-msg",
            "- templates/git/example/tag-msg",
            "- templates/git/example/gitignore",
            "",
            "Templates allow consistent commit messages and tagging workflows.",
        ],
    },
}

COMMON_ROOT_FILES = {
    "README.md": "Project overview and introduction.",
    "CHANGELOG.md": "History of notable changes between releases.",
    "LICENSE": "Project license information.",
    "CONTRIBUTING.md": "Guidelines for contributing to the project.",
    "SECURITY.md": "Security policy and vulnerability reporting instructions.",
    "ROADMAP.md": "Future plans and development roadmap.",
    "TODO.md": "Pending tasks and future improvements.",
    "ABOUT.md": "General information about the project.",
    "AGENTS.md": "Instructions and guidance for AI agents and automation tools.",
    "DEVELOPMENT_GUIDE.md": "Guide for developers working on the project.",
    "ENGINEERING_EXECUTION_POLICY.md": "Engineering execution standards and policies.",
    "EXECUTION_TRACKER.md": "Tracks execution progress or development stages.",
    "pyproject.toml": "Main Python project configuration file.",
    "requirements.txt": "Python package dependencies.",
    "mkdocs.yml": "MkDocs documentation site configuration.",
    "Makefile": "Defines common development, testing, and build commands.",
    "Dockerfile": "Container image build instructions.",
    "Dockerfile.dev": "Development container configuration.",
    "Dockerfile.prod": "Production container configuration.",
    "docker-compose.yml": "Default multi-container Docker configuration.",
    "docker-compose.dev.yml": "Development Docker Compose configuration.",
    "docker-compose.prod.yml": "Production Docker Compose configuration.",
    ".gitignore": "Specifies files and directories ignored by Git.",
    ".dockerignore": "Specifies files excluded from Docker build context.",
    ".editorconfig": "Editor configuration for consistent coding styles.",
    ".prettierrc.json": "Prettier code formatting configuration.",
    ".prettierignore": "Files ignored by Prettier.",
    ".pre-commit-config.yaml": "Pre-commit hooks configuration.",
    ".projectignore": "Ignore rules for project utilities and scanners.",
    ".cz.toml": "Configuration for Commitizen commit conventions.",
    ".cz_changelog.j2": "Commitizen changelog template.",
    ".custor.toml": "Custom configuration file used by project tools.",
    ".gitlab-ci.yml": "GitLab CI/CD pipeline configuration.",
    ".env.example": "Example environment variables configuration.",
    ".gitattributes": "Git file handling and line-ending rules.",
    ".python-version": "Python version used by pyenv.",
    "pytest.ini": "Pytest configuration.",
    "ruff.toml": "Ruff linter configuration.",
    "mypy.ini": "MyPy type checking configuration.",
    "tox.ini": "Multi-environment test configuration.",
}
